<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
           xmlns:tns="http://example.com/host"
           targetNamespace="http://example.com/host"
           elementFormDefault="qualified">
	<xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
	<xs:element name="Document">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Body" type="xs:string"/>
				<xs:element ref="ds:Signature" minOccurs="0"/>
				<xs:element ref="tns:Footer" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Footer" type="xs:string"/>
</xs:schema>
